name: CI/CD with PM2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          # Старт SSH-агента и добавление приватного ключа
          eval $(ssh-agent -s)
          ssh-add - <<< "${SSH_KEY}"

          # Копирование файлов на сервер
          rsync -avz --delete . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/users/maintainer

          # Перезапуск приложения с помощью PM2 на сервере
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'pm2 restart maintainer-bot'
